import Image from 'next/image'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-base-gray-600 text-base-gray-100'>
        <header className='flex items-center justify-center bg-base-gray-700 p-4 w-full h-52'>
          <Image src="/Logo.svg" alt="Logo" width={126} height={48} />
        </header>
        {children}
      </body>
    </html>
  )
}
